### PR TITLE
add funnel example

### PR DESCRIPTION
**Pull request by vndrewlee**
adding a funnel example to the demo site

includes a dashboard, saved views, and data model

will create a build preview once the BigQuery issue is resolved (slack thread)[https://gleannyc.slack.com/archives/CJTJBKP89/p1682634855474139]

### CODE REVIEW

**Comment by nstokoe** [comment]
Once the big query issue is resolved and I can profile the new model I will add it to the hardcoded profiles in the app.

**Comment by vndrewlee** [comment]
https://demo.glean.io/app/p/builds/pCPKgZhk-I4OUc5E

**Comment by nstokoe** [comment]
Sorry, I'm holding this up. Will profile the new model soon.

**Comment by nstokoe** [comment]
PR for hardcoding the metadata: https://github.com/gleannyc/glean/pull/7522

**Comment by nstokoe** [comment]
@vndrewlee the hardcoded metadata was merged so this should be safe to merge into `main` now.

**Comment by vndrewlee** [comment]
(Carlos said I could land in slack DM)

**Pull request merged**
